name: Deploy LiveKit Agent

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install livekit livekit-agents

      - name: Configure LiveKit Agent
        env:
          LIVEKIT_API_KEY: ${{ secrets.LIVEKIT_API_KEY }}
          LIVEKIT_API_SECRET: ${{ secrets.LIVEKIT_API_SECRET }}
        run: |
          echo "Configuring agent..."
          # Optionally generate livekit.toml dynamically if needed
          cat livekit.toml

      - name: Deploy LiveKit Agent
        env:
          LIVEKIT_API_KEY: ${{ secrets.LIVEKIT_API_KEY }}
          LIVEKIT_API_SECRET: ${{ secrets.LIVEKIT_API_SECRET }}
        run: |
          # Update or create the agent in LiveKit
          lk agent update --config livekit.toml || lk agent create --config livekit.toml
